#!/bin/bash
#                           ___      ___                  |
#                         /'___\ __ /\_ \                 |
#     _____   _ __   ___ /\ \__//\_\\//\ \      __        |
#    /\ '__`\/\`'__\/ __`\ \ ,__\/\ \ \ \ \   /'__`\      |
#    \ \ \L\ \ \ \//\ \L\ \ \ \_/\ \ \ \_\ \_/\  __/      |
#     \ \ ,__/\ \_\\ \____/\ \_\  \ \_\/\____\ \____\     |
#      \ \ \/  \/_/ \/___/  \/_/   \/_/\/____/\/____/     |
#       \ \_\                                             |
#        \/_/                                             |

# ────────────────────────────────────────────────────────────────────────────────────────────────────
# ENV Variables: {{{

export EDITOR="nvim"
export TERMINAL="konsole"
export BROWSER="brave-browser"
export EXPLORER="ranger"

export DEV_PATH="$HOME/Development"
export DOTFILES_PATH="$HOME/Development/dotfiles"
export IMAGES_PATH="$HOME/Images"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_LIB_HOME="$HOME/.local/state"
export BIN_PATH="$HOME/.local/bin"

export THEME_BACKGROUND="#11111b"
export THEME_BACKGROUND_ALT="#181825"
export THEME_FOREGROUND="#cdd6f4"
export THEME_SELECTED="#69a1fb"
export THEME_ACTIVE="#9aef94"
export THEME_URGENT="#Ea4769"

# proton bridge and pass
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"

# }}}
# ────────────────────────────────────────────────────────────────────────────────────────────────────

# ────────────────────────────────────────────────────────────────────────────────────────────────────
# ASDF: {{{

export ASDF_DIR="$XDG_DATA_HOME/asdf"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"

export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export ASDF_DEFAULT_TOOL_VERSIONS_FILENAME="$XDG_CONFIG_HOME/asdf/tool-versions"

export ASDF_GEM_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/asdf/default-gems"
export ASDF_NPM_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/asdf/default-npm-packages"

# }}}
# ────────────────────────────────────────────────────────────────────────────────────────────────────

# ────────────────────────────────────────────────────────────────────────────────────────────────────
#  X11 {{{

export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export USERXSESSION="$XDG_CACHE_HOME/x11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/x11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/x11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"
# export XAUTHORITY="$XDG_RUNTIME_DIR/x11/Xauthority"

# }}}
# ────────────────────────────────────────────────────────────────────────────────────────────────────

# ────────────────────────────────────────────────────────────────────────────────────────────────────
#  ZSH {{{

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_STATE_HOME/zsh/history"
export ZSH_COMPDUMP_DIR="$XDG_CACHE_HOME/zsh/"
export ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh/"

export ZSH="$XDG_CONFIG_HOME/oh-my-zsh"
export ZSH_CUSTOM="$XDG_CONFIG_HOME/oh-my-zsh/custom"

# }}}
# ────────────────────────────────────────────────────────────────────────────────────────────────────

# ────────────────────────────────────────────────────────────────────────────────────────────────────
#  LESS {{{

export LESSHISTFILE="$XDG_STATE_HOME/less/history"
export LESSKEY="$XDG_CONFIG_HOME/less/keys"

# Remove history file
export LESS=-R

# colorize manual pages 
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"

# }}}
# ────────────────────────────────────────────────────────────────────────────────────────────────────

# ────────────────────────────────────────────────────────────────────────────────────────────────────
#  Node {{{

export NVM_DIR="$XDG_CONFIG_HOME/nvm"

export NODE_REPL_HISTORY="$XDG_DATA_HOME/node/node_repl_history"

# NPM
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc


# }}}
# ────────────────────────────────────────────────────────────────────────────────────────────────────

# ────────────────────────────────────────────────────────────────────────────────────────────────────
#  PHP {{{

# PHP ENV PATH
# export PATH="/usr/local/opt/php@7.2/bin:$PATH"

# }}}
# ────────────────────────────────────────────────────────────────────────────────────────────────────

# ────────────────────────────────────────────────────────────────────────────────────────────────────
#  PostgreSQL {{{

export PSQLRC="$XDG_CONFIG_HOME/pg/psqlrc"
export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
export PGPASSFILE="$XDG_CONFIG_HOME/pg/pgpass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"

# }}}
# ────────────────────────────────────────────────────────────────────────────────────────────────────

# ────────────────────────────────────────────────────────────────────────────────────────────────────
#  Ruby {{{

export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle"
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/bundle"

export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

export SOLARGRAPH_CACHE="$XDG_CACHE_HOME/solargraph"

# Rails test fix
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# Ruby options - require bundle/setup library to compile gems
# export RUBYOPT="-rbundler/setup"

# fix readline error when installing old ruby versions (2.4.1)
export RUBY_CONFIGURE_OPTS='--with-readline-dir=/home/linuxbrew/.linuxbrew/Cellar/readline/8.2.1/lib'

# }}}
# ────────────────────────────────────────────────────────────────────────────────────────────────────

export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export KDEHOME="$XDG_CONFIG_HOME/kde"

export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"

export RUSTUP_HOME="$XDG_CONFIG_HOME/rustup"
export CARGO_HOME="$XDG_CONFIG_HOME/cargo"

export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/credentials"
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"

export W3M_DIR="$XDG_STATE_HOME/w3m"

export WGETRC="$XDG_CONFIG_HOME/wgetrc"

export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"

export RANGER_LOAD_DEFAULT_RC=false
