#!/bin/bash

shopt -s expand_aliases

function get-pulse-master-metadata() {
wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -o '\[MUTED\]' | awk '{print ($1 == "[MUTED]" ? 1 : 0)}'
}

function a-volume-percent() {
  wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -oP '\d\.\d{2}' | awk '{print $1 * 100}' | bc 
}

function a-status() {
  muted=$(get-pulse-master-metadata)
  volume=$(a-volume-percent)

  if [ "$muted" = 1 ]; then
    echo "muted"
  elif [ "$volume" -lt 50 ]; then
    echo "low"
  else
    echo "high"
  fi
}

subcommand="$1"

if [[ -z "$subcommand" ]]; then
  echo 'No arguments given'
else
  if type "a-$subcommand" > /dev/null 2> /dev/null; then
    eval "a-$subcommand"
  else
    echo 'Unknown subcommand'
  fi
fi
