#!/bin/bash

TMP_FILE="/tmp/eww-mediaplayer.json"
TITLE_MAX_LENGTH=25
ARTIST_MAX_LENGTH=22

shopt -s expand_aliases

SPOTIFY_STATUS=$(playerctl status --player=spotify --format "{{ status }}")
STRAWBERRY_STATUS=$(playerctl status --player=strawberry --format "{{ status }}")

function active_player() {
  if [ "$STRAWBERRY_STATUS" = "Playing" ]; then
    echo "strawberry"
  elif [ "$SPOTIFY_STATUS" = "Playing" ]; then
    echo "spotify"
  elif [ "$STRAWBERRY_STATUS" = "Paused" ]; then
    echo "strawberry"
  elif [ "$SPOTIFY_STATUS" = "Paused" ]; then
    echo "spotify"
  fi
}

function player_data() {
  player_param="--player=$(active_player)"
  playerctl "$1" "$player_param" --format "{{ $2 }}"
}

function mp-art-url() {
  url=$(player_data metadata "mpris:artUrl")
  player=$(active_player)

  if [ "$player" = "strawberry" ]; then
    path="$url"
    file_name=$(basename "$path")
  elif [ "$player" = "spotify" ]; then
    file_name="spotify-cover-${url##*/}"
    path="/tmp/$file_name.jpg"
    wget -O $path "$url"
  fi

  result_path="/tmp/$file_name-44px.jpg"
  convert "$path" -resize 64x51^ -gravity center -extent 64x51 "$result_path"

  echo "$result_path"
}

function mp-progress() {
  current_time=$(player_data position "position")
  duration=$(player_data metadata "mpris:length")

  echo "scale=2; $current_time / $duration * 100" | bc
}

function get_call_index() {
  key=$1
  json=$(cat "$TMP_FILE")
  value=$(echo "$json" | jq -r ".${key}_index")
  echo "$value"
}

function set_call_index() {
  key=$1
  index=$2
  echo "{ \"${key}_index\": $index }" > "$TMP_FILE"
}

function mp-title() {
  title="$(player_data metadata "title")"

  if [ "${#title}" -gt $TITLE_MAX_LENGTH ]; then
    # last_index=$(get_call_index "title")
    #
    # if [ -z "$last_index" ] || [ "$(echo "$last_index + $TITLE_MAX_LENGTH + 1" | bc)" -gt "${#title}" ]; then
    #   index=0
    # else
    #   index=$(echo "$last_index + 1" | bc)
    # fi
    #
    # set_call_index "title" "$index"
    #
    # echo "${title:index:TITLE_MAX_LENGTH}"
    echo "${title:0:TITLE_MAX_LENGTH}..."
  else
    echo "$title"
  fi
}

function mp-artist() {
  artist=$(player_data metadata "lc(artist)")

  # get length of artists
  if [ "${#artist}" -gt $ARTIST_MAX_LENGTH ]; then
    artist="${artist:0:$ARTIST_MAX_LENGTH}..."
  fi

  echo "$artist"
}

function mp-running() {
  status=$(player_data status "uc(status)")

  if [ -z "$status" ] || [ "$status" = "stopped" ]; then
    echo 0
  else
    echo 1
  fi
}

# formats the time in miliseconds to a human readable format m:ss without leading zeros
function mp-duration() {
  # in miliseconds
  duration=$(player_data metadata "mpris:length")

  formatted_duration=$(date -d@"$((duration / 1000000))" -u +%M:%S)
  formatted_duration=$(echo "$formatted_duration" | sed 's/^0*//')

  echo "$formatted_duration"
}

alias mp-current-time='player_data position "duration(position)"'

subcommand="$1"

if [[ -z "$subcommand" ]]; then
  echo 'No arguments given'
else
  if type "mp-$subcommand" > /dev/null 2> /dev/null; then
    eval "mp-$subcommand"
  else
    echo 'Unknown subcommand'
  fi
fi
