#!/bin/bash

EWW_BIN="/usr/bin/eww"

hide_windows() {
  ${EWW_BIN} close system calendar system audio bluetooth_menu language_menu
}

calendar() {
  LOCK_FILE="$HOME/.cache/eww-calendar.lock"

  run() {
    ${EWW_BIN} open calendar
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE" ]]; then
    hide_windows
    touch "$LOCK_FILE"
    run && echo "ok good!"
  else
    ${EWW_BIN} close calendar
    rm "$LOCK_FILE" && echo "closed"
  fi
}

system() {
  LOCK_FILE_MEM="$HOME/.cache/eww-system.lock"

  run() {
    ${EWW_BIN} open system
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE_MEM" ]]; then
    hide_windows
    touch "$LOCK_FILE_MEM"
    run && echo "ok good!"
  else
    ${EWW_BIN} close system 
    rm "$LOCK_FILE_MEM" && echo "closed"
  fi
}

audio() {
  LOCK_FILE_AUDIO="$HOME/.cache/eww-audio.lock"

  run() {
    ${EWW_BIN} open audio
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE_AUDIO" ]]; then
    hide_windows
    touch "$LOCK_FILE_AUDIO"
    run && echo "ok good!"
  else
    ${EWW_BIN} close audio
    rm "$LOCK_FILE_AUDIO" && echo "closed"
  fi
}

bluetooth() {
  declare -gx LOCK_FILE_BLUETOOTH="$HOME/.cache/eww-bluetooth.lock"

  run() {
    ${EWW_BIN} open bluetooth_menu 
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE_BLUETOOTH" ]]; then
    hide_windows
    touch "$LOCK_FILE_BLUETOOTH"
    run && echo "ok good!"
  else
    ${EWW_BIN} close bluetooth_menu
    rm "$LOCK_FILE_BLUETOOTH" && echo "closed"
    unset LOCK_FILE_BLUETOOTH
  fi
}

language() {
  declare -gx LOCK_FILE_LANGUAGE="$HOME/.cache/eww-language.lock"

  run() {
    ${EWW_BIN} open language_menu 
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE_LANGUAGE" ]]; then
    hide_windows
    touch "$LOCK_FILE_LANGUAGE"
    run && echo "ok good!"
  else
    ${EWW_BIN} close language_menu
    rm "$LOCK_FILE_LANGUAGE" && echo "closed"
    unset LOCK_FILE_LANGUAGE
  fi
}

if [ "$1" = "calendar" ]; then
  calendar
elif [ "$1" = "system" ]; then
  system
elif [ "$1" = "audio" ]; then
  audio
elif [ "$1" = "bluetooth" ]; then
  bluetooth
elif [ "$1" = "language" ]; then
  language
fi
