#!/bin/bash

# EWW_BIN="$HOME/.local/bin/eww/eww"
EWW_BIN="$HOME/eww/target/release/eww"

hide_windows() {
  ${EWW_BIN} -c $HOME/.config/eww/bar close system calendar system music_win audio_ctl bluetooth_menu
}

calendar() {
  LOCK_FILE="$HOME/.cache/eww-calendar.lock"

  run() {
    ${EWW_BIN} -c $HOME/.config/eww/bar open calendar
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE" ]]; then
    hide_windows
    touch "$LOCK_FILE"
    run && echo "ok good!"
  else
    ${EWW_BIN} -c $HOME/.config/eww/bar close calendar
    rm "$LOCK_FILE" && echo "closed"
  fi
}

system() {
  LOCK_FILE_MEM="$HOME/.cache/eww-system.lock"

  run() {
    ${EWW_BIN} -c $HOME/.config/eww/bar open system 
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE_MEM" ]]; then
    hide_windows
    touch "$LOCK_FILE_MEM"
    run && echo "ok good!"
  else
    ${EWW_BIN} -c $HOME/.config/eww/bar close system 
    rm "$LOCK_FILE_MEM" && echo "closed"
  fi
}

music() {
  LOCK_FILE_SONG="$HOME/.cache/eww-song.lock"

  run() {
    ${EWW_BIN} -c $HOME/.config/eww/bar open music_win 
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE_SONG" ]]; then
    hide_windows
    touch "$LOCK_FILE_SONG"
    run && echo "ok good!"
  else
    ${EWW_BIN} -c $HOME/.config/eww/bar close music_win
    rm "$LOCK_FILE_SONG" && echo "closed"
  fi
}

audio() {
  LOCK_FILE_AUDIO="$HOME/.cache/eww-audio.lock"

  run() {
    ${EWW_BIN} -c $HOME/.config/eww/bar open audio_ctl 
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE_AUDIO" ]]; then
    hide_windows
    touch "$LOCK_FILE_AUDIO"
    run && echo "ok good!"
  else
    ${EWW_BIN} -c $HOME/.config/eww/bar close audio_ctl
    rm "$LOCK_FILE_AUDIO" && echo "closed"
  fi
}

bluetooth() {
  declare -gx LOCK_FILE_BLUETOOTH="$HOME/.cache/eww-bluetooth.lock"

  run() {
    ${EWW_BIN} -c $HOME/.config/eww/bar open bluetooth_menu 
  }

  # Open widgets
  if [[ ! -f "$LOCK_FILE_BLUETOOTH" ]]; then
    hide_windows
    touch "$LOCK_FILE_BLUETOOTH"
    run && echo "ok good!"
  else
    ${EWW_BIN} -c $HOME/.config/eww/bar close bluetooth_menu
    rm "$LOCK_FILE_BLUETOOTH" && echo "closed"
    unset LOCK_FILE_BLUETOOTH
  fi
}

if [ "$1" = "calendar" ]; then
  calendar
elif [ "$1" = "system" ]; then
  system
elif [ "$1" = "music" ]; then
  music
elif [ "$1" = "audio" ]; then
  audio
elif [ "$1" = "bluetooth" ]; then
  bluetooth
fi
