#!/usr/bin/env bash

set -e

CONFIG="build/install.conf.yaml"
DOTBOT_DIR="build/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive

DOTBOT_BIN="${BASEDIR}/${DOTBOT_DIR}/bin/dotbot"
ASDF_BIN="${BASEDIR}/build/dotbot-asdf/asdf.py"
YAY_BIN="${BASEDIR}/build/dotbot-yay/yay.py"

"${DOTBOT_BIN}" -d "${BASEDIR}" -p "${ASDF_BIN}" -p "${YAY_BIN}" -c "${CONFIG}" "${@}"
