#!/usr/bin/env bash

set -e

CONFIG="build/install.conf.yaml"
DOTBOT_DIR="build/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive

DOTBOT_BIN="${BASEDIR}/${DOTBOT_DIR}/bin/dotbot"
ASDF_DIR="${BASEDIR}/build/dotbot-asdf"
PACMAN_BIN="${BASEDIR}/build/dotbot-pacaur/pacaur.py"

"${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir "${ASDF_DIR}" -p "${PACMAN_BIN}" -c "${CONFIG}" "${@}"
