#!/bin/bash

EWW="$BIN_PATH/usr/eww"

# Run eww daemon if not running already
if [ ! "$(pidof "$EWW")" ]; then
  echo 'EWW daemon'
	$EWW daemon
	sleep 1
fi

if $EWW windows | grep "/*bar/"; then
  $EWW --restart open bar
else
  $EWW reload bar
fi
