bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +10%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -10%
bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioMicMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindsym $mod+Return exec kitty
bindsym $mod+Shift+q kill
bindsym $mod+space exec ~/.config/rofi/launch.sh
bindsym $mod+Shift+e exec ~/.config/rofi/launch.sh powermenu
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
bindsym $mod+s split h
bindsym $mod+v split v
bindsym $mod+f fullscreen toggle
bindsym $mod+Shift+space floating toggle
bindsym $mod+Shift+x [floating] move scratchpad
bindsym $mod+x scratchpad show
bindsym $mod+q layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
bindsym $mod+a focus parent
bindsym $mod+Shift+a focus child
bindsym $mod+Shift+c reload
bindsym --release $mod+Shift+n exec dunstctl close-all
bindsym $mod+Ctrl+l exec $HOME/.config/sway/bin/lock
bindsym Print exec grim -g "$(slurp)" - | wl-copy --type image/png
bindsym Shift+Print exec grim - | wl-copy --type image/png
bindsym Control+Print exec ~/.config/sway/bin/capture-file
set $mode_system (l)ock, (e)xit, (s)uspend, (h)ibernate, (r)eboot, (Shift+s)hutdown
bindsym $mod+0 mode "$mode_system"
mode "$mode_system" {
    bindsym l exec $HOME/.config/sway/bin/lock, mode "default"
    bindsym e exit
    bindsym s exec systemctl suspend, mode "default"
    bindsym h exec systemctl hibernate, mode "default"
    bindsym r exec systemctl reboot, mode "default"
    bindsym Shift+s exec systemctl poweroff, mode "default"
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
mode "resize" {
    bindsym h resize shrink width 10 px or 10 ppt
    bindsym j resize grow height 10 px or 10 ppt
    bindsym k resize shrink height 10 px or 10 ppt
    bindsym l resize grow width 10 px or 10 ppt
    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+r mode "default"
}
bindsym $mod+r mode "resize"
