#!/bin/sh
# shellcheck disable=SC1091

# https://man.archlinux.org/man/xkeyboard-config.7
setxkbmap -layout us,cz,ja -variant qwerty
setxkbmap -option 'grp:ctrl_space_toggle'

if [ "$(lsusb | grep -cE 'ErgoDox|OpenMoko')" = 0 ]; then
  setxkbmap -option 'grp_led:caps'
  setxkbmap -option 'caps:swapescape'
fi

# https://wiki.archlinux.org/title/Xrandr
# xrandr --dpi 96 \
  #   --output DisplayPort-2 --auto --preferred --primary \
  #   --output DVI-D-0       --auto --panning 2880x1620+3840+0 --right-of DisplayPort-2 \
  #   --output HDMI-A-0      --auto --panning 3840x2160+6720+0 --right-of DVI-D-0

xrandr --dpi 96 \
  --output DisplayPort-2 --auto --preferred --primary \
  --output DVI-D-0       --auto --right-of DisplayPort-2 \
  --output HDMI-A-0      --auto --right-of DVI-D-0

xdg_home="$HOME/.config/x11"

if [ -f "$xdg_home/xresources" ]; then
  xrdb -merge "$xdg_home/xresources"
fi

if [ -f "$xdg_home/xprofile" ]; then
  . "$xdg_home/xprofile"
fi

exec i3
