#!/bin/sh
# shellcheck disable=SC1091

# https://man.archlinux.org/man/xkeyboard-config.7
setxkbmap -layout us,cz,ja -variant qwerty
setxkbmap -option 'grp:ctrl_space_toggle'

if [ "$(lsusb | grep ErgoDox)" = 0 ]; then
  setxkbmap -option 'grp_led:caps'
  setxkbmap -option 'caps:swapescape'
fi

xdg_home="$HOME/.config/x11"
if [ -f "$xdg_home/xresources" ]; then
  xrdb -merge "$xdg_home/xresources"
fi

if [ -f "$xdg_home/xprofile" ]; then
  . "$xdg_home/xprofile"
fi
