#!/bin/sh
# shellcheck disable=SC1091

setxkbmap -layout us,cz -variant ,qwerty
setxkbmap -option 'grp_led:caps'
# setxkbmap -option 'grp:caps_toggle

xrdb "$HOME/.config/x11/xresources"

source "$HOME/.config/x11/xprofile"
