#!/bin/sh

export LANG="en_US.UTF-8"
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"
export XMODIFIERS="@im=ibus"

export QTWEBENGINE_REMOTE_DEBUGGING=8080

# export GDK_SCALE=2
# export GDK_DPI_SCALE=0.5
# export QT_AUTO_SCREEN_SET_FACTOR=0
# export QT_SCALE_FACTOR=2
# export QT_FONT_DPI=96
