# ======= BREW =============================

emulate sh -c 'source /etc/profile'

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# ======= RubyOnRails =============================

# Rails test fix
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# ======= NVM =============================

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"  # This loads nvm

# ======= I3wm =============================

# Set i3-sensible-terminal
export TERMINAL="konsole"

# ======= PHP =============================

# PHP ENV PATH
# export PATH="/usr/local/opt/php@7.2/bin:$PATH"

# ======= Scripts =============================

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# ======= RVM =============================

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# ======= ZSH =============================

# if running zsh
if [ -n "$ZSH_VERSION" ]; then
    # include .zshrc if it exists
    if [ -f "$HOME/.zshrc" ]; then
	    source "$HOME/.zshrc"
    fi
fi
