# Aliases
source ~/.shell/aliases.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Settings
source ~/.zsh/settings.zsh

source ~/.zsh/omz.zsh

source ~/.zsh/vi.zsh

source ~/.zsh/env_variables.zsh
