# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
  source ~/.zsh/p10k.zsh
fi

# Settings
source ~/.zsh/settings.zsh

# Ruby specific
source ~/.zsh/langs.zsh

# Zsh vi settings
source ~/.zsh/vi.zsh

# Aliases
source ~/.shell/aliases.sh
